### ISSUE TITLE
Build differences

### ISSUE THREAD

**Issue by swift502** [kripken/ammo.js#204] opened 2018-05-29 20:54 UTC
Hi,

I managed to build, and it works fine. I do get a new warning when using my build:
![image](https://user-images.githubusercontent.com/24359130/40684918-03c3dab4-6393-11e8-9286-9f4883a8495f.png)
...but everything seems to work as it should.

But the build files are completely different.
The official build starts with `c;c||(c=typeof Ammo !== 'undefined' ? Ammo : {});var aa={}`
my build starts with `Module=typeof Ammo!=="undefined"?Ammo:{};var moduleOverrides={};`
Here's the full diff: https://www.diffchecker.com/5djMXszu, the files are completely different.

Any idea why that is? Is it a problem since I just want to test ammo.idl changes with this? Are there different ways to build Ammo?

Thanks.

**Comment by kripken** [comment] 2018-05-29 22:46
The difference is due to emscripten changes - that asm.js error is a regression in 1.38.2, and should be fixed in 1.38.4 (which is being tagged today). Sorry for that!

Another difference is that the official builds are built with closure, add `closure` to the params for `make.py`. That shrinks the JS some more, and effects like you mention in the second paragraph.

**Comment by swift502** [comment] 2018-05-30 04:33
Thanks for clarifying! I'll try it right away. :slightly_smiling:

**Closed** 2018-05-30 04:34 UTC
