### ISSUE TITLE
New cmake build system removed addFunction support

### ISSUE THREAD

**Issue by MackeyK24** [kripken/ammo.js#323] opened 2020-08-01 15:31 UTC
I was export addFunction using make.py

```
  if add_function_support:
    args += ' -s RESERVED_FUNCTION_POINTERS=20 -s EXTRA_EXPORTED_RUNTIME_METHODS=["addFunction"]'
```

So i can do stuff like
```
                    const contactAddedCallbackPtr = Ammo.addFunction((cp:any, colObj0Wrap:any, partId0:number, index0:number, colObj1Wrap, partId1:number, index1:number) => {
                        // NOTE: KEEP FOR REFERENCE
                        // colObj0Wrap = Ammo.wrapPointer(colObj0Wrap, Ammo.btCollisionObjectWrapper);
                        // colObj1Wrap = Ammo.wrapPointer(colObj1Wrap, Ammo.btCollisionObjectWrapper);
                        // const colobj0:any = colObj0Wrap.getCollisionObject();
                        // const colobj1:any = colObj1Wrap.getCollisionObject();
                        // if (colobj0 != null && colobj1 != null) {
                        //    const colshape0:any = colobj0.getCollisionShape();
                        //    const colshape1:any = colobj1.getCollisionShape();
                        // }
                        if (physicsplugin.world.adjustInternalEdgeContacts) {
                            physicsplugin.world.adjustInternalEdgeContacts(cp, colObj1Wrap, colObj0Wrap, partId1, index1);
                            return true;
                        } else {
                            return false;
                        }
                    });
```

Now with the new cmake -B builds ... it does not support 

```
$ cmake -B builds -DRESERVED_FUNCTION_POINTERS=20 -DEXTRA_EXPORTED_RUNTIME_METHODS=["addFunction"] -DTOTAL_MEMORY=134217728

```

So how am i supposed to get Ammo.addFunction back ???

**Comment by kripken** [comment] 2020-08-01 23:29
I think CMake lets you add linker flags using something like
```cmake
cmake '-DCMAKE_EXE_LINKER_FLAGS=-s EXTRA_EXPORTED_RUNTIME_METHODS=["addFunction"]'
```
(not 100% sure about the quotations though,).

**Comment by MackeyK24** [comment] 2020-08-02 01:53
I tried
```
cmake -B builds -DADD_FUNCTION_SUPPORT=1
```

I already tried edit the CMakeLists.txt

```
set(EMCC_ARGS
  --extern-pre-js ${AMMO_FRONT_MATTER_FILE}
  --llvm-lto 1
  --post-js glue.js
  -O3
  -s ALLOW_MEMORY_GROWTH=${ALLOW_MEMORY_GROWTH}
  -s EXPORTED_RUNTIME_METHODS=["UTF8ToString"]
  -s EXPORT_NAME="Ammo"
  -s MODULARIZE=1
  -s NO_EXIT_RUNTIME=1
  -s NO_FILESYSTEM=1
  -s RESERVED_FUNCTION_POINTERS=20
  -s EXTRA_EXPORTED_RUNTIME_METHODS=["addFunction"]
  -s TOTAL_MEMORY=${TOTAL_MEMORY})
```

Both did not work... In the result build **Ammo.addFunction** is **undefined** in javascript

Used to work just fine before changing the build system and using make.py

**Comment by MackeyK24** [comment] 2020-08-02 01:54
I cant re build my ammo with out AddFunction Support :(

**Comment by MackeyK24** [comment] 2020-08-02 02:25
Really weird... i get these messages
```
-- WARNING: you are using the obsolete 'GLU' package, please use 'OpenGL' instead
```

Do i now need some sort of OpenGL Library... It does not say anything about installing OpenGL library in the instructions

**Comment by MackeyK24** [comment] 2020-08-02 02:44
Yo @kripken ... Do you do side work. If so, are you willing to build versions of Ammo.js for me... I will pay :)

I used to build them myself, but for some reason i cant build Ammo.js on my mac any more (even without AddFunction). It seems when i just try rebuild ammo.js and to my existing application that was using previous build ammo. just FAIL.

So it must be something with the new build system and my mac. I really need to apply these Raycast Vehicle fixes i have and build versions with addFunction support. I normally build a 64, 128, 256, 512, 1024 and 2048 MB builds.

I am stuck and cant go on without new build. Can you help, please ?

Again.. I can pay

**Comment by kripken** [comment] 2020-08-02 02:49
@MackeyK24 I wouldn't have time to make custom builds myself, sorry. Did you try what I suggested in my comment? But editing the CMakeList.txt should work too.

Maybe @ianpurvis has an idea what could be wrong for you?

**Comment by MackeyK24** [comment] 2020-08-02 03:01
Yep i tried your suggestion. Did not work.

What is the deal with GLUE... Is there some specific install i need gor for that... I have the latest xcode with command line tools installed. So GLUT should be on my machine.

I found an older version of Ammo.js that was still building with make.py and now it give me error as well.
```
Traceback (most recent call last):
  File "make.py", line 220, in <module>
    build()
  File "make.py", line 163, in build
    emscripten.Building.emcc('glue.cpp', args, 'glue.o')
AttributeError: 'module' object has no attribute 'Building'
```

Its going from bad to worse for me... Do you have any idea what can be going wrong ?

**Comment by ianpurvis** [comment] 2020-08-02 04:21
@MackeyK24 Hey, sorry you are having trouble. I have not used addFunction myself, but I want to help you if I can. Send me a DM!

> 
> ```
> 
> Traceback (most recent call last):
> 
>   File "make.py", line 220, in <module>
> 
>     build()
> 
>   File "make.py", line 163, in build
> 
>     emscripten.Building.emcc('glue.cpp', args, 'glue.o')
> 
> AttributeError: 'module' object has no attribute 'Building'
> 
> ```
> 
☝️ I've seen this issue before, it's breakage between make.py and newer emscripten. I believe it was fixed in
https://github.com/kripken/ammo.js/pull/316 before we deleted make.py, can you cherry pick that patch?

**Comment by ianpurvis** [comment] 2020-08-02 05:28
> `-- WARNING: you are using the obsolete 'GLU' package, please use 'OpenGL' instead`

^ Don't sweat this warning (it occurs when bullet 2.82 tries to detect GLU even though ammo does not care about GLU).

I tried to test your issue on master like this:

```
cmake -B builds -DCLOSURE=1 -DADD_FUNCTION_SUPPORT=1
cmake --build builds
npx http-server -p 3000
open -a safari 'http://localhost:3000/examples/webgl_demo_vehicle/index.html'
```

Then I set a breakpoint on line 55 (after ammo has been loaded) and successfully found `addFunction` in the console:

```
> typeof Ammo.addFunction => 'function'
```

I wonder if you have cached files interfering with cmake... Can you try the above after `rm -rf builds` ?

Btw- if you ever need to debug the compiler commands, cmake will respect `EMCC_DEBUG`:

```
EMCC_DEBUG=1 cmake --build builds
```

**Comment by MackeyK24** [comment] 2020-08-02 08:36
Could it be something missing from my machine ???

Note: I tried the modded make.py

but got different error:

```
make: *** [config.status] Error 77
Traceback (most recent call last):
  File "make.py", line 194, in <module>
    build()
  File "make.py", line 159, in build
    emscripten.make(['make', '-j', str(CORES)])
  File "/users/mackey/tools/emsdk/upstream/emscripten/tools/building.py", line 382, in make
    run_process(args, stdout=stdout, stderr=stderr, env=env, shell=WINDOWS, **kwargs)
  File "/users/mackey/tools/emsdk/upstream/emscripten/tools/shared.py", line 203, in run_process
    result.check_returncode()
  File "/users/mackey/tools/emsdk/upstream/emscripten/tools/shared.py", line 176, in check_returncode
    raise Py2CalledProcessError(returncode=self.returncode, cmd=self.args, output=self.stdout, stderr=self.stderr)
tools.shared.Py2CalledProcessError: Command '['make', '-j', '24']' returned non-zero exit status 2

```

**Comment by MackeyK24** [comment] 2020-08-02 08:45
What the holy heck is going on with Emscripten and Building... Has something changed... It all used to work fine. I needed to make small change in raycast vehicle and re build. Everything just went to shit.

So i tried to re-install emscripten and now get 
```
Installing SDK 'sdk-releases-upstream-536568644fd67d53778f6111fdd5f64ad3f4c539-64bit'..
Installing tool 'node-12.18.1-64bit'..
Error: Downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v12.18.1-darwin-x64.tar.gz': <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>
Warning: Possibly SSL/TLS issue. Update or install Python SSL root certificates (2048-bit or greater) supplied in Python folder or https://pypi.org/project/certifi/ and try again.
Installation failed!

```

I never had any issue with a Python SSL Certificate before...

This is really weird

**Comment by MackeyK24** [comment] 2020-08-02 09:26
I tried the command above verbatim

Still no addFunction

![Screen Shot 2020-08-01 at 11 24 27 PM](https://user-images.githubusercontent.com/5013415/89120035-64afc580-d44e-11ea-9540-758481640597.png)

**Comment by MackeyK24** [comment] 2020-08-02 09:39
Yo @ianpurvis  ... I really need help. I didnt realize that the ammo project was going to change so much when i started my project that using Ammo.js as the main physics engine. Heck i thought since what 2.82 version and not version 3 it was pretty stable and that was it on the building. 

Now my project is so heavily dependent on ammo.js (which now i cant even build anymore). I am way to far along to switch out the physics engine. I am so screwed :(

Can you please help me figure out what the heck is going on with EMSCRIPTEN/AMMO building on my machine. Or can i send you my updates to ammo.js and you build it for me. I will pay you. Can send payment via Paypal asap

**Comment by ianpurvis** [comment] 2020-08-02 14:20
@MackeyK24 Thanks for the test- it looks like the issue is that the top level `Ammo()` function stopped assigning `window.Ammo` to the loaded module (this used to be injected by the `bundle.py` script).

Your console shows

```
> Ammo
< function (Ammo) {
  Ammo = Ammo || {};


var b;b||(b=typeof Ammo !== 'undefined' ? Ammo : {});
var Promise=function(){function a(){}function c(v,J){return function(){v.appl ...
```

But once the module has been loaded by `Ammo().then(function(Ammo) {` you should see this:

```
> Ammo
< {ready: d, HEAP8: Int8Array, HEAP16: Int16Array, HEAP32: Int32Array, HEAPU8: Uint8Array, …}
```

If you inspect Ammo from inside the `then` block, you should see module is ready and `addFunction` should also be present.

I'll see if I can write a quick fix for this.

**Comment by ianpurvis** [comment] 2020-08-02 15:20
@MackeyK24 See #324, maybe you can try these changes locally until the PR is merged?

You can also probably hack this by changing your ammo initialization-

```javascript
Ammo().then(function(Ammo) {
    window.Ammo = Ammo

    ...
}
```

**Comment by MackeyK24** [comment] 2020-08-02 22:32
I think there is still something wrong with my machine... When i try to build i get this... It makes the ammo.js but it fails in my project

```
Mackeys-Mac-Pro:ammo mackey$ source /users/mackey/tools/emsdk/emsdk_env.sh --build=Release
Adding directories to PATH:
PATH += /users/mackey/tools/emsdk
PATH += /users/mackey/tools/emsdk/upstream/emscripten
PATH += /users/mackey/tools/emsdk/node/12.18.1_64bit/bin
PATH += /users/mackey/tools/emsdk/python/3.7.4_64bit/bin

Setting environment variables:
EMSDK = /users/mackey/tools/emsdk
EM_CONFIG = /users/mackey/tools/emsdk/.emscripten
EM_CACHE = /users/mackey/tools/emsdk/upstream/emscripten/cache
EMSDK_NODE = /users/mackey/tools/emsdk/node/12.18.1_64bit/bin/node
EMSDK_PYTHON = /users/mackey/tools/emsdk/python/3.7.4_64bit/bin/python3
Mackeys-Mac-Pro:ammo mackey$ export EMSCRIPTEN=$EMSDK/upstream/emscripten
Mackeys-Mac-Pro:ammo mackey$ cmake -B builds -DCLOSURE=1 -DADD_FUNCTION_SUPPORT=1
OPENGL FOUND
nul
-- WARNING: you are using the obsolete 'GLU' package, please use 'OpenGL' instead
CMake Warning (dev) at /Applications/CMake.app/Contents/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (OpenGL)
  does not match the name of the calling package (GLU).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.17/Modules/FindOpenGL.cmake:427 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /Applications/CMake.app/Contents/share/cmake-3.17/Modules/FindGLU.cmake:12 (include)
  bullet/CMakeLists.txt:325 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY OPENGL_INCLUDE_DIR) 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/Mackey/Desktop/ammo/builds
Mackeys-Mac-Pro:ammo mackey$ 

```

**Comment by MackeyK24** [comment] 2020-08-02 23:14
Question... What advantage does using closure have (-DCLOSURE=1) ???

**Comment by MackeyK24** [comment] 2020-08-02 23:47
Yo @ianpurvis ... I manually added you fixes to put Ammo on the window object. And now it compiles ... BUT now when i actually call addFunction it get an error: 

```
Cannot read property 'slice' of undefined
```

When called like so:

```
const contactAddedCallbackPtr = Ammo.addFunction((cp:any, colObj0Wrap:any, partId0:number, index0:number, colObj1Wrap, partId1:number, index1:number)

```

BUt it at least builds now

**Comment by ianpurvis** [comment] 2020-08-03 02:31
> Cannot read property 'slice' of undefined

^ Can you get any stack trace for this error? 

I would not expect any of the build changes to break this. But I guess it's possible that generating ammo with different emscripten SDK versions could create a low level change.

I will test your code later tonight to see if I can figure it out.

If you get into an emergency, you could branch ammo from the git commit that was last working for you. Then roll back your emsdk install- you should be able to run make.py without patching if you use emscripten <= 1.39.11

**Comment by MackeyK24** [comment] 2020-08-03 02:56
Please try build with addFunction then create a callback like above using Ammo.addFunction and see what you get... In the meantime.. I will try and rollback to my last working make.py version with emsdk 1.39.11 and see what happens there as well

Thanks you so much @ianpurvis :)

**Comment by ianpurvis** [comment] 2020-08-03 17:48
@MackeyK24 No problem. I spent some time with this and finally wrote an automated test for `Ammo.addFunction` and also `btDiscreteDynamicsWorld.prototype.setContactAddedCallback`. You can check it out in #325, it's a very basic test but hopefully it helps. 

So I think that the `Cannot read property 'slice' of undefined` error is coming from outside of ammo. If you grep for `slice`, maybe you can find it in that code path? In a perfect world, a stack trace for that error would show the offending location too.

**Closed** 2020-08-19 18:07 UTC

**Comment by ianpurvis** [comment] 2020-08-23 17:14
@MackeyK24 I finally encountered the `Cannot read property 'slice' of undefined` error while testing `addFunction` and emscripten 2.0. Looks like the issue happens if `addFunction` gets called without its signature string argument. Since emscripten 1.37.34, a second arg is required for Wasms built with LLVM:

```
v1.37.34: 02/16/2018
--------------------
 - `addFunction` is now supported on LLVM wasm backend, but when being used on
   the wasm backend, you need to provide an additional second argument, a Wasm
   function signature string. Each character within a signature string
   represents a type. The first character represents the return type of a
   function, and remaining characters are for parameter types.
    - 'v': void type
    - 'i': 32-bit integer type
    - 'j': 64-bit integer type (currently does not exist in JavaScript)
    - 'f': 32-bit float type
    - 'd': 64-bit float type
   For asm.js and asm2wasm you can provide the optional second argument, but it
   isn't needed. For that reason this isn't a breaking change, however,
   providing the second argument is recommended so that code is portable across
   all backends and modes.
```

I've added some [constants](https://github.com/kripken/ammo.js/pull/332/commits/df5c96afad163cf1cba2c6e0eee45466ad1ab56b#diff-dbc661acd1fa44dca1497f392e4a2aafR1-R4) for each signature in #332
